openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Statistics Server"
  description: Literally a statisics server

paths:
  /moo:
    get:
      summary: Check if the server is alive
      responses:
        "200":
          description: If the server moos back, it means that it is alive.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        "429":
          description: Too many requests
        "500":
          description: Internal server error

  /activity:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: clientVersion
        required: true
        schema:
          type: string
      - in: header
        name: activeManagers
        required: true
        schema:
          type: integer
      - in: header
        name: activeSettings
        required: true
        schema:
          type: integer
      - in: header
        name: language
        required: true
        schema:
          type: string
    post:
      summary: Submit client activity data
      responses:
        "200":
          description: Activity data was submitted.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /package/install:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: packageId
        required: true
        schema:
          type: string
      - in: header
        name: managerName
        required: true
        schema:
          type: string
      - in: header
        name: sourceName
        required: true
        schema:
          type: string
      - in: header
        name: operationResult
        schema:
          type: string
          enum:
            - SUCCESS
            - FAILED
            - CANCELED
        required: true
      - in: header
        name: eventSource
        required: true
        schema:
          type: string
    post:
      summary: A package was installed
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /package/download:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: packageId
        required: true
        schema:
          type: string
      - in: header
        name: managerName
        required: true
        schema:
          type: string
      - in: header
        name: sourceName
        required: true
        schema:
          type: string
      - in: header
        name: operationResult
        schema:
          type: string
          enum:
            - SUCCESS
            - FAILED
            - CANCELED
        required: true
      - in: header
        name: eventSource
        required: true
        schema:
          type: string
    post:
      summary: A package was downloaded
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /package/update:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: packageId
        required: true
        schema:
          type: string
      - in: header
        name: managerName
        required: true
        schema:
          type: string
      - in: header
        name: sourceName
        required: true
        schema:
          type: string
      - in: header
        name: operationResult
        schema:
          type: string
          enum:
            - SUCCESS
            - FAILED
            - CANCELED
        required: true
    post:
      summary: A package was updated
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /package/uninstall:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: packageId
        required: true
        schema:
          type: string
      - in: header
        name: managerName
        required: true
        schema:
          type: string
      - in: header
        name: sourceName
        required: true
        schema:
          type: string
      - in: header
        name: operationResult
        schema:
          type: string
          enum:
            - SUCCESS
            - FAILED
            - CANCELED
        required: true
    post:
      summary: A package was uninstalled
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /package/details:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: packageId
        required: true
        schema:
          type: string
      - in: header
        name: managerName
        required: true
        schema:
          type: string
      - in: header
        name: sourceName
        required: true
        schema:
          type: string
      - in: header
        name: eventSource
        required: true
        schema:
          type: string
    post:
      summary: A package was shown on the package details page
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /package/share:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: packageId
        required: true
        schema:
          type: string
      - in: header
        name: managerName
        required: true
        schema:
          type: string
      - in: header
        name: sourceName
        required: true
        schema:
          type: string
      - in: header
        name: eventSource
        required: true
        schema:
          type: string
    post:
      summary: A user has shared a package
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /bundles/export:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: bundleType
        schema:
          type: string
          enum:
            - UBUNDLE
            - JSON
            - YAML
            - XML
        required: true
    post:
      summary: A bundle was created and exported
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.

  /bundles/import:
    parameters:
      - in: header
        name: clientId
        required: true
        schema:
          type: string
      - in: header
        name: bundleType
        schema:
          type: string
          enum:
            - UBUNDLE
            - JSON
            - YAML
            - XML
    post:
      summary: A bundle was opened
      responses:
        "200":
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.




  /report:
    parameters:
      - in: header
        name: apiKey
        required: true
        schema:
          type: string
    get:
      summary: Get a report of the data on the server
      responses:
        "200":
          description: The report has been generated and returned as a JSON object
          content:
            application/json:
              schema:
                type: object
        "403":
          description: Access denied.
        "406":
          description: Invalid or missing parameter(s).
        "429":
          description: Too many requests
        "500":
          description: Internal server error.
