openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Statistics Server'
  description: Literally a statisics server

paths:
  /moo:
    get:
      summary: Check if the server is alive
      responses:
        '200':
          description: If the server moos back, it means that it is alive.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties: 
                  message:
                    type: string
        '500':
          description: Internal server error


  /activity:
    post:
      summary: Submit client activity data
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
               - clientId
               - clientVersion
               - activeManagers
               - activeSettings
              properties:
                clientId:
                  type: string
                clientVersion:
                  type: string
                activeManagers:
                  type: string
                activeSettings:
                  type: string
      responses:
        '200':
          description: Activity data was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified.
        '500':
          description: Internal server error

  /install:
    post:
      summary: Submit that a client has installed a package
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
               - clientId
               - packageId
               - managerName
               - sourceName
              properties:
                clientId:
                  type: string
                packageId:
                  type: string
                managerName:
                  type: string
                sourceName:
                  type: string
      responses:
        '200':
          description: Package information was submitted. The addition may be ignored if the data is invalid, but the sender (you) won't be notified. Invalid data could be, for example, when a client X submits twice the install of the same package. 
        '500':
          description: Internal server error
          
  /report:
    get:
      summary: Submit that a client has installed a package
      responses:
        '200':
          description: The report has been generated and returned as a JSON object
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal server error
